export const projects = [
  {
    title: 'ERP Pizzaria',
    description: "ERP for a pizza company, featuring dynamic mobile app homepage construction for delivery orders, order management, inventory control, and sales reporting.",
    longDescription: "ERP for a pizza company, featuring dynamic mobile app homepage construction for delivery orders, order management, inventory control, and sales reporting. Integrated with Brazilian tax invoice system (NFe) for issuing and receiving electronic invoices.",
    image: '/images/ERPPizza/1.png',
    images: [
      '/images/ERPPizza/1.png',
      '/images/ERPPizza/2.png',
      '/images/ERPPizza/3.png',
      '/images/ERPPizza/4.png',
      '/images/ERPPizza/5.png',
      '/images/ERPPizza/6.png',
      '/images/ERPPizza/7.png',
      '/images/ERPPizza/8.png',
      '/images/ERPPizza/9.png',
      '/images/ERPPizza/10.png',
      '/images/ERPPizza/11.png',
      '/images/ERPPizza/12.png',
      '/images/ERPPizza/13.png',
      '/images/ERPPizza/14.png',
      '/images/ERPPizza/15.png',
      '/images/ERPPizza/16.png',
      '/images/ERPPizza/17.png',
      '/images/ERPPizza/18.png',
      '/images/ERPPizza/19.png'
    ],
    tags: ['TypeScript', 'React', 'Next.js', 'TailwindCss', 'Prisma', 'Libs'],
    id: 1,
  },
    {
    title: 'Omni 2.0',
    description: "Intuitive, practical and confident tool to attend costumers with statistics monitoring, WhatsApp broadcast lists, and internal chat among agents.",
    longDescription: "An evolution of Omni 1.0, in this new version, the layout has been completely redesigned for a more intuitive, organized, and practical experience. We have also implemented new features such as a dashboard for improved monitoring, internal chat among agents, WhatsApp broadcast list, and light/dark theme.",
    image: '/images/Omni2.0/Screenshot_14.png',
    images: ['/images/Omni2.0/Screenshot_14.png', '/images/Omni2.0/Screenshot_2.png', '/images/Omni2.0/Screenshot_4.png', '/images/Omni2.0/Screenshot_5.png', '/images/Omni2.0/Screenshot_6.png', '/images/Omni2.0/Screenshot_8.png', '/images/Omni2.0/Screenshot_9.png', '/images/Omni2.0/Screenshot_10.png', '/images/Omni2.0/Screenshot_13.png'],
    tags: ['Vue3', 'Quasar', 'Websocket', 'Libs'],
    // source: 'https://github.com/lordarcadius/website',
    // visit: 'https://project.vipuljha.com/website/',
    id: 3,
  },
  {
    title: 'ViaExpressa',
    description: "App for managing a delivery company. It allows users to place orders, track order status, and generate reports on customers, employees, or the system overall. ",
    longDescription: "App for a motorcycle delivery company. A dashboard to track ongoing orders, waypoint system, and calculations for order value. A range of reports to have a real understanding of values and quantities. The app has access for administrators, employees, and customers, each with different permissions.",
    image: '/images/Delivery/Screenshot_1.png',
    images: ['/images/Delivery/Screenshot_1.png', '/images/Delivery/Screenshot_2.png', '/images/Delivery/Screenshot_6.png', '/images/Delivery/Screenshot_10.png', '/images/Delivery/Screenshot_14.png', '/images/Delivery/Screenshot_20.png',],
    tags: ['TypeScript', 'React', 'Next.js', 'Prisma', 'Libs'],
    // source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    // visit: 'https://project.vipuljha.com/covid/',
    id: 0,
  },
  // BuStop
  {
    title: 'Omni 1.0',
    description: "Made a usable and confident tool to attend costumers and show statistics data about the timing to answers messages and related datas",
    longDescription: "Software for call center support where we handle everything in a single app... WhatsApp (multiple APIs), web chat, phone calls, and email. The software includes pause systems, status updates, classification of interactions, scheduling, and the ability to monitor the number of interactions in the queue.",
    image: '/images/Omni1.0/Screenshot_1.png',
    images: ['/images/Omni1.0/Screenshot_1.png', '/images/Omni1.0/Screenshot_2.png', '/images/Omni1.0/Screenshot_3.png',],
    tags: ['Vue2', 'Vuetify', 'Websocket', 'Libs'],
    // source: 'https://github.com/lordarcadius/website',
    // visit: 'https://project.vipuljha.com/website/',
    id: 2,
  },
  {
    title: 'Calculadora do Crochê',
    description: 'A simple web application for calculating labor and expenses for crocheters, arriving at the result with hourly labor cost, product price, and profit.',
    longDescription: 'A straightforward web application for calculating labor and expenses for crochet artists, arriving at the result with hourly labor cost, product price, and profit. Application created using basic resources and front-end only.',
    image: '/images/CalculadoraCroche/Screenshot_1.jpg',
    images: ['/images/CalculadoraCroche/Screenshot_1.jpg', '/images/CalculadoraCroche/Screenshot_3.jpg'],
    tags: ['Vue3', 'Quasar'],
    id: 4
  }
];

export const TimeLineData = [
  { year: 2018, text: 'Started an internship in computer networking at my city hall.' },
  { year: 2019, text: 'Enrolled in college for computer networking and got promoted to network technician.' },
  { year: 2020, text: 'Started working at the Network Operations Center (NOC) of an internet service provider.' },
  { year: 2021, text: 'Graduated from college and began my journey as a developer.' },
  { year: 2022, text: 'Secured my first full-time job as a developer, working on software development for call center management.' },
  { year: 2023, text: 'Became a mid-level fullstack developer and published my first React Native app on the App Store and Play Store.' },
  { year: 2024, text: 'Started studying Swift to develop iOS apps and in the second half of the year, became a fullstack analyst developer.' },
  { year: 2025, text: 'Started my post-graduation in software architecture and solution architecture with AI.' }
];
